// <auto-generated />
using System;
using FarmaTech.BD.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarmaTech.BD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FarmaTech.BD.Datos.Entity.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetalleVentas");
                });

            modelBuilder.Entity("FarmaTech.BD.Datos.Entity.Drogueria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CanalContacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Droguerias");
                });

            modelBuilder.Entity("FarmaTech.BD.Datos.Entity.Empleada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empleadas");
                });

            modelBuilder.Entity("FarmaTech.BD.Datos.Entity.IngresoMercaderia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("DrogueriaId")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDrogueria")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleada")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrogueriaId");

                    b.HasIndex("EmpleadaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("IngresosMercaderia");
                });

            modelBuilder.Entity("FarmaTech.BD.Datos.Entity.NotaPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("DrogueriaId")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadaId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDrogueria")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleada")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrogueriaId");

                    b.HasIndex("EmpleadaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("NotasPedido");
                });

            modelBuilder.Entity("FarmaTech.BD.Datos.Entity.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("FarmaTech.BD.Datos.Entity.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpleada")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadaId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("FarmaTech.BD.Datos.Entity.DetalleVenta", b =>
                {
                    b.HasOne("FarmaTech.BD.Datos.Entity.Producto", "Producto")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaTech.BD.Datos.Entity.Venta", "Venta")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("FarmaTech.BD.Datos.Entity.IngresoMercaderia", b =>
                {
                    b.HasOne("FarmaTech.BD.Datos.Entity.Drogueria", "Drogueria")
                        .WithMany("IngresosMercaderia")
                        .HasForeignKey("DrogueriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaTech.BD.Datos.Entity.Empleada", "Empleada")
                        .WithMany("IngresosMercaderia")
                        .HasForeignKey("EmpleadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaTech.BD.Datos.Entity.Producto", "Producto")
                        .WithMany("IngresosMercaderia")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drogueria");

                    b.Navigation("Empleada");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FarmaTech.BD.Datos.Entity.NotaPedido", b =>
                {
                    b.HasOne("FarmaTech.BD.Datos.Entity.Drogueria", "Drogueria")
                        .WithMany("NotasPedido")
                        .HasForeignKey("DrogueriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaTech.BD.Datos.Entity.Empleada", "Empleada")
                        .WithMany("NotasPedido")
                        .HasForeignKey("EmpleadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaTech.BD.Datos.Entity.Producto", "Producto")
                        .WithMany("NotasPedido")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drogueria");

                    b.Navigation("Empleada");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FarmaTech.BD.Datos.Entity.Venta", b =>
                {
                    b.HasOne("FarmaTech.BD.Datos.Entity.Empleada", "Empleada")
                        .WithMany("Ventas")
                        .HasForeignKey("EmpleadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleada");
                });

            modelBuilder.Entity("FarmaTech.BD.Datos.Entity.Drogueria", b =>
                {
                    b.Navigation("IngresosMercaderia");

                    b.Navigation("NotasPedido");
                });

            modelBuilder.Entity("FarmaTech.BD.Datos.Entity.Empleada", b =>
                {
                    b.Navigation("IngresosMercaderia");

                    b.Navigation("NotasPedido");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("FarmaTech.BD.Datos.Entity.Producto", b =>
                {
                    b.Navigation("DetallesVenta");

                    b.Navigation("IngresosMercaderia");

                    b.Navigation("NotasPedido");
                });

            modelBuilder.Entity("FarmaTech.BD.Datos.Entity.Venta", b =>
                {
                    b.Navigation("DetallesVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
